ASP-111/Controllers/FrontController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASPProject.Controllers
{
    public class FrontController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ASP-111/Controllers/HomeController.cs
using ASPProject.Models;
using ASPProject.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASPProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IDateService _dateService;
        private readonly TimeService _timeService;
        private readonly DateTimeService _dateTimeService;
        private readonly Validation _validatorService = new();
        public HomeController(ILogger<HomeController> logger,IDateService dateService, TimeService timeService, DateTimeService dateTimeService, Validation validation)
        {
            _logger = logger;
            _dateService = dateService;
            _timeService = timeService;
            _dateTimeService = dateTimeService;
            _validatorService = validation;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Intro()
        {
            return View();
        }
        public IActionResult Razor()
        {
            return View();
        }
        public ViewResult Sessions()
        {
            if(HttpContext.Session.Keys.Contains("StoredValue"))
            {
                ViewData["StoredValue"] = HttpContext.Session.GetString("StoredValue");
            }
            else
            {
                ViewData["StoredValue"] = "";
            }
            return View();
        }
        public RedirectToActionResult RemoveSession()
        {
            HttpContext.Session.Remove("StoredValue");
            return RedirectToAction(nameof(Sessions));
        }
        public IActionResult SetSession()
        {
            HttpContext.Session.SetString("StoredValue","Данные сессии");
            return RedirectToAction(nameof(Sessions));
        }
        public IActionResult Services()
        { 
            ViewData["date"] = _dateService.GetDate();
            ViewData["time"] = _timeService.Gettime();
            ViewData["datetime"] = _dateTimeService.GetNow();

            ViewData["date-hash"] = _dateService.GetHashCode();
            ViewData["time-hash"] = _timeService.GetHashCode();
            ViewData["datetime-hash"] = _dateTimeService.GetHashCode();
            ViewData["validation"] = new bool[] {
            _validatorService.ValidateLogin("NormalLogin1"),
            _validatorService.ValidateLogin("Normal_Login_2"),
            _validatorService.ValidateLogin("In-valid login"),
            _validatorService.ValidateLogin("$ invalid ++")
            };
            ViewData["ctrl-hash"] = this.GetHashCode();
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
        public ViewResult Data()
        {
            return View();
        }

        public ViewResult Middleware()
        {
            ViewData["marker"] = HttpContext.Items.ContainsKey("marker")
                ? HttpContext.Items["marker"] : "Нет маркера";
            return View("Middleware");
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP-111/Views/Home/Data.cshtml
@{
    ViewData["Title"] = "DataContext";
}

<div class="text-center">
    <h1 class="display-4">Конткест данных</h1>

</div>
<ul>
    <li>
        Подключаем пакеты NuGet для работы с EntityFramework(MySql)
        <ol>
            <li>Microsoft.EntityFrameworkCore</li>
            <li>Microsoft.EntityFrameworkCore</li>
            <li>Pomelo.EntityFrameworkCore.MySql</li>
        </ol>
    </li>
    <li>
        Создаем папку Data,в ней класс DataContext(наследник DbContext)
    </li>
    <li>
        Поскольку контекст данных будет попадать в контейнер служб,его 
        конфигурацией также будет руководить контейнер.Поэтому в классе 
        объявляем конструктор с опциями<br /> 
        <code>
            public DataContext(DbContextOptions options) : base(options)<br />
            {<br />
            }<br />
        </code>
    </li>
    <li>
        База данных на PlanetScale одна,поєтому будем разделять таблицы по схемам.
        Для этого в контексте указываем:<br />
        <code>
            protected override void OnModelCreating(ModelBuilder modelBuilder)<br />
            {<br />
            modelBuilder.HasDefaultSchema("asp");<br />
            }<br />
        </code>
        Это означает что таблица нашего проекта будут группироваться в схеме "asp"
        </li>
        <li>
             В Program.cs указываем подключение и его настройки,главная особенность
             МайСкл состоит в том,что он не поддерживает схемы,поэтому группировку
             таблиц со схемами заменяем на префиксное именование(названия таблиц
             начинаются с названия схемы)
        </li>
        <li>Создаем папку Data/Entities,в ней класс User,
            в контексте добавляем свойство Users
        </li>
        <li>
            Создаем миграцию
        </li>
</ul>

ASP-111/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
  
</div>
<h3><a href="/Home/Intro">Введение в ASP</a></h3>
<h3><a href="/Home/Razor">Razor</a></h3>
<h3><a asp-controller="Home" asp-action="Services">Службы и зависимости</a></h3>
<h3><a asp-controller="Home" asp-action="Data">Data Context</a></h3>
<h3><a asp-controller="Home" asp-action="Sessions">Sessions</a></h3>
<h3><a asp-controller="Home" asp-action="Middleware">Middleware</a></h3>

<hr/>

<h3><a asp-controller="Front" asp-action="Index">Распределенная архитектура</a></h3>


<p>
    <b>ASP</b> - Active Server Pages - комплекс или фреймворк .NET 
    для разработки серверных приложений
</p>
<p>
    Отличительной особенностью является согласование работы 
    различных частей приложения по совпадению имен классов,представлений с названием файлов,
    папок и частей URL - запроса.
</p>
<p>
    !! Если проект создан с названием,содержащим спецсимволы,то
    необходимо поправить ссылку на стили в _layout.cshtml
</p>

ASP-111/Views/Home/Intro.cshtml
@{
    ViewData["Title"] = "Введение";
}

<div class="text-center">
    <h1 class="display-4">Введение в ASP</h1>
    
</div>

ASP-111/Views/Home/Middleware.cshtml
@{
    ViewData["Title"] = "Middleware";
}

<div class="text-center">
    <h1 class="display-4">Middleware:ПО промежуточного слоя</h1>
</div>

<p>
    Идея Middleware заключается в создании некого бктылочного горлышка,
    через которое проходят все запросы(для всех контроллеров, методов и т.п)
</p>

<p>
    Middleware образует цепочку, в которой каждое звено передает управление следующему.
    Последнее звено запускает обратный ход передавая ответ по всем звеньям в обратном 
    порядке.Существует возможность прервать обработку на любом из звеньев.
</p>
<p>
     Middleware может быть много,поэтому их описывают в отдельной папки проекта
    Классы Middleware включаются инструкциями <code>UseMiddleware&lt;TheClass()</code>,
    однако традиция - использовать классы расширения, позволяющие создать инструкции
    <code>UseTheClass()</code>.По этому в файле Middleware часто идут два класса - сама логика
    и класс-расширение
</p>
<p>
    Один из примеров Middleware - маркер.Просто в контекст устанавливается некоторое значение,
    и это есть признак того, что запрос прошел правильный путь.
    <!--маркер: <strong>@ViewData["marker"]</strong>-->
</p>
<p>
    Использование служб (инъекция) в Middleware. Поскольку конструктор классов
    Middleware *занят* под связывание цепочки вызовов Middleware,инъекция через него
    служб невозможна.Также Middleware имеет Scope Singleton (не пересоздается,всегда
    один объект) поэтому инъекция в его конструктор служб с другим временем существования
    невозможна.В итоге, инъекция в Middleware происходит в методе InvokeAsync / Invoke

</p>

<p><strong>@ViewData["marker"]</strong></p>

ASP-111/Views/Home/Razor.cshtml
@{
    ViewData["Title"] = "Razor";
}

<div class="text-center">
    <h1 class="display-4">Введение в Razor</h1>

</div>
<p>
    Одной из необходимых задач серверной разработки является расширение
    ыозможностей HTML с дополнением его алгоритмическими конструкциями.
    В АSР исторически использовались спецтеги &lt;asp, однако им на смену пришел
    синтаксис Razer
</p>
<p>
    <b>Razor</b> - специальный инструмент для включения в хтмл с# кода.
    Файлы с данными инструкциями имеют файл расширения .CSHTML
    Данные файлы "заполняются" на сервере,в браузер приходит чистый хтмл(без спецконструкций)
    Основными командным символом Razer является &commat;
    поэтому в хтмл для его вставки используется сущность <b>&amp;commat;</b>


</p>
<h3>Выражения</h3>
<p>
    Выражении (в программировании) - инструкция, имеющая результат
    Razor позволяет вычислять выражения и выводить их результат в хтмл
    при помощи конструкции &commat;():<br />
    <code>
        &commat;(2 + 3) = @(2 + 3)
    </code>
    В простых выражениях круглые скобки можно не ставить,однако тогда границы выражения определяют Razor и не всегда так,как хотелось бы нам

</p>
<h3>Блоки кода</h3>
<p>
    Инструкции,не требующие вывода результатов в HTML,помещаются в блоки &commat;{}.
    В этих блоках возможны практически любые команды .NET(c#)
    Однако,применение лишней активности в представлениях не рекомендуется
    паттерном MVC
</p>
<p>
    @{
        int x = 10;
        x += 5;
    }
    x = @x
</p>
<h3>Условная верстка</h3>
<p>
    Средствами Razor можно создавать(или не создавать) блоки верстки в зависимости
    от программных условий.Для этого использкется комманда &commat;if(){}
    Для множественного выбора можно использовать &commat;sweatch(){}
</p>
@if (x < 10)
{
    <b>Этот блок будет при х &lt; 10</b>
}
else
{
    <b>Этот блок будет при х &ge; 10</b>
}
<h3>Циклическая верстка</h3>
<p>
    Основа современных сайтов - работа с массивами данных.
    В Razor есть все виды циклов с#
    &commat;for(){}
    &commat;while(){}
    &commat;foreach(){}
</p>
@{
    string[] s = new string[5] { "1", "2", "3", "4", "5" };
}
@for (int i = 0; i < s.Length; i++)
{
    int j = i + 1;
    <p>@j. @s[i]</p>
}
<ul>
    @for (int i = 0; i < s.Length; i++)
    {
        int j = i + 1;
        <li>@j. @s[i]</li>
    }
</ul>
<table>
    <tbody>

        @for (int i = 0; i < s.Length; i++)
        {
            int j = i + 1;
            <tr>
                <td>@j. </td>
                <td>@s[i]</td>
            </tr>
        }

    </tbody>
</table>
<br />
@for (int i = 0; i < s.Length; i++)
{
    int j = i + 1;
    <div>@j. @s[i]</div>
}

ASP-111/Views/Home/Services.cshtml
@using ASPProject.Services
@inject IDateService dateService
@inject TimeService timeService
@inject DateTimeService dateTimeService
@inject Validation validation
@{
    ViewData["Title"] = "Services";
}

<div class="text-center">
    <h1 class="display-4">Службы и зависимости</h1>
</div>

<p>
    SOLID - набор рекомендаций по архитектурной композиции проекта.
    <b>D</b> (DIP) - принцип инверсии зависимостей.Принцип рекомендует
    не создавать зависимости от реализаций,а использовать для этого 
    абстракции - интерфейсы
</p>
<p>
    Службы (в ООП) - объекты глобального типа, доступные из различных
    частей проекта.В отличии от глобальных переменных службы имеют различные
    области существования (Scope)<br />
    <b>Singleton</b> - максимальное время существования,различные объекты получают
    ссылку на один и тот же объект службы.
    <b>Scoped</b> - время существования в течении обработки запроса(как у конструктора).
    С новым запросом создается новый объект.
    <b>Transient</b> - каждое орбращение к службе создает новый объект,
    в разных точках инъекции объекты всегда разные
</p>
<p>
    Работа со службами состоит из нескольких этапов
</p>
<ul>
    <li>Традиционно, службы помещаются в отдельную папку</li>
    <li>Описываются классы служб, их методы</li>
    <li>
        Классы регистрируются в контейнере служб (в Програм.цс между
        <code>var builder = ...</code> и <code>var app = builder.Build();</code>)
    </li>
    <li>
        Службы запрашиваются в других объектах, чаще всего - в контроллерах.
        По умолчанию в первом контроллере подключается служба логирования,можно использовать
        ее как пример
    </li>
    <li>
        Также службы могут инжектироваться в представления, Razor имеет для этого
        инструкцию &commat;inject
    </li>
</ul>
<p>
    Как это работает:
    Program.cs выполняется один раз при старте сервера (запуск приложения).
    В этот момент происходит регестрация всех служб (но объекты пока не создаются).
    Контроллеры пересоздаются каждый раз при новом запросе,
    при создании происходит запрос на объект службы и в этот момент он будет создаваться / либо использоваться ранее созданный объект службы.
</p>
<p>
    Для контроля новых\старых объектов можно использовать хеш-коды.
</p>
<table>
    <thread>
        <tr>
            <th>Служба</th>
            <th>Хеш-код(в контроллере)</th>
            <th>Хеш-код(в представлении)</th>
            <th>Комментарий</th>
        </tr>
    </thread>
    <tbody>
        <tr>
            <td>HomeController</td>
            <td>@ViewData["ctrl-hash"]</td>
            <td>----</td>
            <td>Изменяется при обновлении страницы</td>
        </tr>
        <tr>
            <td>DateService</td>
            <td>@ViewData["date-hash"]</td>
            <td>@dateService.GetHashCode()</td>
            <td>Singleton - не изменяется при обновлениях(только при перезапуске)</td>
        </tr>
        <tr>
            <td>TimeService</td>
            <td>@ViewData["time-hash"]</td>
            <td>@timeService.GetHashCode()</td>
            <td>Scope - изменяется при обновлениях,но одинаковый во всех местах</td>
        </tr>
        <tr>
            <td>DateTimeService</td>
            <td>@ViewData["datetime-hash"]</td>
            <td>@dateTimeService.GetHashCode()</td>
            <td>Transient - изменяется во всех местах и при обновлениях</td>
        </tr>
    </tbody>
</table>
<br />
<p>
    Данные от службы DateService: <b>@ViewData["date"]</b>
</p>
<p>
    Данные от службы DateService: <b>@ViewData["time"]</b>
</p>
<p>
    Данные от службы DateService: <b>@ViewData["datetime"]</b>
</p>
<p>
    <b>Validation:</b>
</p>


@{
    var correct = ViewData["validation"] as bool[];
    for (int i = 0; i < correct.Length; i++)
    {

        <p>@correct[i]</p>

    }
}

ASP-111/Views/Home/Sessions.cshtml
@{
    ViewData["Title"] = "Sessions";
}

<div class="text-center">
    <h1 class="display-4">Sessions</h1>
</div>


<p>
    Сессии - термин,обозначающий действия,ограниченные некоторым промежутком
    времени.HTTP-сессии - механизмЮпозволяющий сохранять данные в течении
    некоторого времени,большего,чем время запроса
</p>
<p>
    Зачем?
    HTTP - сервер каждый запрос обслуживает как новый,контроллеры пересоздаются.
    Можно сказать,что каждый запрос перезапускает приложение. При этом актуален вопрос - 
    а как сохранить данные между запросами?
</p>
<p>
    При старте сессии в каждый ответ на запрос пользователя включается специальные данные
    - Cookie. Это заголовки паекта, которые по стандарту должны будут включаться 
    браузером во все повторные запросы к данному серверу.Если в запросе есть уже Cookie,
    то по его значению восстанавливаются данные,сохраненные при прошлом запросе. 
</p>
<p>
    <a href="https://learn.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-7.0">Настройка сессии</a>
</p>
<ul>
    <li>Подключение службы хранения в памяти <code>builder.Services.AddDistributedMemoryCache();</code></li>
    <li>
        Настройка Cookie <code>
            builder.Services.AddSession(options =>
            {
            options.IdleTimeout = TimeSpan.FromSeconds(10);
            options.Cookie.HttpOnly = true;
            options.Cookie.IsEssential = true;
            });
        </code>
    </li>
    <li>Включение сессий <code>app.UseSession();</code></li>
</ul>

<p>
    После настройки и включении сессий, в контексте становится доступным свойство 
    Session. Обращение к контексту происходит по-разному в разных местах
    (контроллер, представление, служба и т.п.) но во всех местах сессия доступна.
    Сессия позволяет сохранять данные по принципу ключ-значение,получать или удалять их
</p>
<p>
    Данные в сессии: @ViewData["StoredValue"] <br/>
    <a asp-action="SetSession">Установить данные</a>
    <a asp-action="RemoveSession">Удалить данные</a>
</p>
<p>
    Основные направления по использованию сессии:
    а) сброс параметров - когда форма передает данные,они "прикрепляются"
    к запросу: видны в URL строке или в теле пакета.Обычно после обработки 
    данных производят перенаправление на адрес без параметров.
    Такие сессии ограничивают небольшим временем - еденицы секунд<br/>
    б) хранение данных, введенных пользователем. В частности данных входа в систему.
    Это позволяет "запоминать" пользователя и его данные. Такие сессии
    имеют большее время существования, ограничения - только политика сайта.
</p>